### ISSUE TITLE
power fist + pickaxe module and picking Thermal Expansion blocks

### ISSUE THREAD

**Issue by corepb** [EnderMediaDev/The-1.7.10-Pack#878]
Hello!

When I am trying to use power fist with pickaxe module installed it's not recognized - I can't use it as an ordinary pickaxe. I hope that's something you can fix guys in the best pack ever made.

Thanks!

**Comment by xJon** [comment]
There are some minor bugs with the MPS version the pack uses. Fortunately, in the next update of the modpack we will switch to the master branch of MPS, which has a lot of fixes to many issues.
There's nothing we can do currently, just wait :)

**Comment by corepb** [comment]
Hello!

Same thing with 0.8.1 version.

**Comment by xJon** [comment]
Should be fixed in v0.8.2

**Comment by corepb** [comment]
Thanks for the info xJon! :) Looking forward for new release!

**Comment by xJon** [comment]
Just be sure to read this about v0.8.2: http://www.technicpack.net/status/362375

**Comment by xJon** [comment]
Should be fixed in v0.8.2.

**Comment by ciak2009** [comment]
Nope, it didn't fix it, because you suck, and all the things are broken.

**Comment by xJon** [comment]
Please forgive @ciak2009 for his uncontrollable actions.
