### ISSUE TITLE
Crash Report - Help please

### ISSUE THREAD

**Issue by martinegui** [EnderMediaDev/The-1.7.10-Pack#913]
Hey guys,
I just updated to the new version ( v0.8.1).
When I tried to load my world ( Last login at v0.8.0), the loading world screen appears and when the words "Building Terrain" shows... CRASH!
I tried to downgrade to v0.8.0 but then crash before de MENU, i cant even see if my wolrd still working at v0.8.0.

LOG from the crash (v0.8.1): http://pastebin.com/gySsNpcZ

Any ideas how to fix it?

**Comment by martinegui** [comment]
I did 1 more test and I cant even create a new world, any help?
I dont know if i paste the correct info at the pastebin but the log was to big to paste completed.

**Comment by xJon** [comment]
Just try to reinstall it should fix itself :)

**Comment by martinegui** [comment]
Still not working, I tried to use the reinstall button from launcher and not working.
The crash LOG: http://pastebin.com/uVh0Nxiz
Should I erase manually the modpack?
Any ideas how to fix?

I,m using Windows 10 could be this the problem?

**Comment by martinegui** [comment]
Nevermind, I deleted completely the modpack ( I only create a backup from paste "saves" ) and now is working, thanks for you help.

**Comment by xJon** [comment]
:+1:
